import express from 'express';
import cors from 'cors';
import * as dotenv from 'dotenv';
import { PlanTripRequestSchema, ItinerarySchema } from './validation.ts';
import { generateItinerary } from './ai.ts';
import { buildPrompt } from './prompt.ts';

// Load environment variables from .env
dotenv.config();

const app = express();

// Enable CORS so the local frontend can communicate with the backend
app.use(cors());

// Parse incoming JSON payloads
app.use(express.json());

const PORT = process.env.PORT || 3000;

// Health check endpoint
app.get('/api/health', (_req, res) => {
  res.json({ status: 'ok', time: new Date().toISOString() });
});

// Trip Planner endpoint
app.post('/api/plan-trip', async (req, res) => {
  console.log('[SERVER] Received plan-trip request.');

  // 1. Validate the user input payload
  const requestValidation = PlanTripRequestSchema.safeParse(req.body);
  if (!requestValidation.success) {
    const errorMsg = requestValidation.error.errors[0]?.message || 'Invalid trip description input.';
    return res.status(400).json({
      error: {
        code: 'INVALID_REQUEST',
        message: errorMsg
      }
    });
  }

  const { prompt } = requestValidation.data;
  const mockModeHeader = req.headers['x-mock-mode'] as string | undefined;

  try {
    // 2. Build the system prompt
    const fullPrompt = buildPrompt(prompt);

    // 3 & 4. Call the LLM (or mock) and fetch raw response
    const rawText = await generateItinerary(fullPrompt, mockModeHeader);

    // 5. Check if response is empty
    if (!rawText || rawText.trim() === '') {
      return res.status(502).json({
        error: {
          code: 'INVALID_AI_RESPONSE',
          message: 'No itinerary was generated. Please try again.'
        }
      });
    }

    // 6. Attempt to parse JSON (and strip markdown wrappers if LLM injected them)
    let parsedJson: any;
    try {
      let cleanedText = rawText.trim();
      // Remove any markdown block wrapping like ```json ... ```
      if (cleanedText.startsWith('```')) {
        cleanedText = cleanedText
          .replace(/^```(json)?\s*/i, '')
          .replace(/\s*```$/, '')
          .trim();
      }
      parsedJson = JSON.parse(cleanedText);
    } catch (parseError) {
      console.error('[SERVER] Failed to parse LLM response text as JSON:', rawText);
      return res.status(502).json({
        error: {
          code: 'INVALID_AI_RESPONSE',
          message: "Couldn't understand the itinerary generated by AI."
        }
      });
    }

    // 7. Validate structured output using Zod
    const validationResult = ItinerarySchema.safeParse(parsedJson);
    if (!validationResult.success) {
      console.error('[SERVER] Zod validation failed for LLM response:', validationResult.error.format());
      return res.status(502).json({
        error: {
          code: 'INVALID_SCHEMA',
          message: 'The AI response did not match the required itinerary structure.'
        }
      });
    }

    // 8. Return validated JSON to the frontend
    return res.json(validationResult.data);

  } catch (error: any) {
    console.error('[SERVER ERROR]:', error.message || error);

    const errorMessage = error.message || '';

    // Handle missing API Key
    if (errorMessage.includes('API_KEY_MISSING')) {
      return res.status(500).json({
        error: {
          code: 'INTERNAL_ERROR',
          message: 'The Gemini API Key is missing. Please create a .env file and add GEMINI_API_KEY.'
        }
      });
    }

    // Handle rate limits / quota issues
    if (errorMessage.includes('429') || errorMessage.includes('rate limit') || errorMessage.includes('quota')) {
      return res.status(429).json({
        error: {
          code: 'RATE_LIMITED',
          message: 'The AI service rate limit was exceeded. Please wait a moment and try again.'
        }
      });
    }

    // Handle LLM timeouts or standard API errors
    return res.status(502).json({
      error: {
        code: 'AI_ERROR',
        message: 'Something went wrong while planning your trip. The AI service failed to respond.'
      }
    });
  }
});

// Start the Express server
app.listen(PORT, () => {
  console.log(`[SERVER] Express backend running at http://localhost:${PORT}`);
});
